TLTN/BagBag/Models/PaymentMethod.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BagBag.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentMethod
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PaymentMethod()
        {
            this.Orders = new HashSet<Order>();
        }
    
        public int PaymentId { get; set; }
        public string PaymentName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Orders { get; set; }
    }
}

TLTN/BagBag/Areas/Management/Controllers/PaymentMethodsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Data.Entity.Validation;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using BagBag.Models;

namespace BagBag.Areas.Management.Controllers
{
    public class PaymentMethodsController : BaseController
    {
        private MyBagBagEntities db = new MyBagBagEntities();

        // GET: Management/PaymentMethods
        public ActionResult Index()
        {
            return View(db.PaymentMethods.ToList());
        }

        // GET: Management/PaymentMethods/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            PaymentMethod paymentMethod = db.PaymentMethods.Find(id);
            if (paymentMethod == null)
            {
                return HttpNotFound();
            }
            return View(paymentMethod);
        }

        // GET: Management/PaymentMethods/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Management/PaymentMethods/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "PaymentId,PaymentName")] PaymentMethod paymentMethod)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    db.PaymentMethods.Add(paymentMethod);
                    db.SaveChanges();
                }
                catch (DbEntityValidationException dbEx)
                {
                    foreach (var validationErrors in dbEx.EntityValidationErrors)
                    {
                        foreach (var validationError in validationErrors.ValidationErrors)
                        {
                            System.Console.WriteLine("Property: {0} Error: {1}", validationError.PropertyName, validationError.ErrorMessage);
                        }
                    }
                }
                return RedirectToAction("Index");
            }

            return View(paymentMethod);
        }

        // GET: Management/PaymentMethods/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            PaymentMethod paymentMethod = db.PaymentMethods.Find(id);
            if (paymentMethod == null)
            {
                return HttpNotFound();
            }
            return View(paymentMethod);
        }

        // POST: Management/PaymentMethods/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "PaymentId,PaymentName")] PaymentMethod paymentMethod)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    db.Entry(paymentMethod).State = EntityState.Modified;
                    db.SaveChanges();
                }
                catch (DbEntityValidationException dbEx)
                {
                    foreach (var validationErrors in dbEx.EntityValidationErrors)
                    {
                        foreach (var validationError in validationErrors.ValidationErrors)
                        {
                            System.Console.WriteLine("Property: {0} Error: {1}", validationError.PropertyName, validationError.ErrorMessage);
                        }
                    }
                }
                return RedirectToAction("Index");
            }
            return View(paymentMethod);
        }

        // GET: Management/PaymentMethods/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            PaymentMethod paymentMethod = db.PaymentMethods.Find(id);
            if (paymentMethod == null)
            {
                return HttpNotFound();
            }
            return View(paymentMethod);
        }

        // POST: Management/PaymentMethods/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            PaymentMethod paymentMethod = db.PaymentMethods.Find(id);
            try
            {
                db.PaymentMethods.Remove(paymentMethod);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            catch (Exception e)
            {
                TempData["msg1"] = "<script>alert('Can not Delete Record');</script>";
                e.ToString();
            }
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

TLTN/BagBag/Areas/Management/Views/PaymentMethods/Create.cshtml
@model BagBag.Models.PaymentMethod

@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/Management/Views/Shared/_AdministratorLayout.cshtml";
}

<h2 class=" text-center">Information's Payment Method</h2>
<div><a href="@Url.Action("Index","PaymentMethods")" class="btn btn-info">Manage</a></div>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
   
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.PaymentName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PaymentName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PaymentName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-info" />
            </div>
        </div>
    </div>
}

TLTN/BagBag/Areas/Management/Views/PaymentMethods/Delete.cshtml
@model BagBag.Models.PaymentMethod

@{
    ViewBag.Title = "Delete";
    Layout = "~/Areas/Management/Views/Shared/_AdministratorLayout.cshtml";
}

<h3 class="text-center">Are you sure</h3>
<div>
   
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.PaymentName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PaymentName)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

    <div class="form-actions no-color">
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a href="@Url.Action("Index","PaymentMethods")" class="btn btn-info">Manage</a>
    </div>
    }
</div>

TLTN/BagBag/Areas/Management/Views/PaymentMethods/Details.cshtml
@model BagBag.Models.PaymentMethod

@{
    ViewBag.Title = "Details";
    Layout = "~/Areas/Management/Views/Shared/_AdministratorLayout.cshtml";
}

<h2 class=" text-center">Information's Payment Method</h2>
<a href="@Url.Action("Index","Products")" class="btn btn-info">Manage</a>

<div>
    
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.PaymentName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PaymentName)
        </dd>

    </dl>
</div>
<p>
    <a href="@Url.Action("Edit", "PaymentMethods", new { id = Model.PaymentId })" class="btn btn-success">Edit</a>
</p>

TLTN/BagBag/Areas/Management/Views/PaymentMethods/Edit.cshtml
@model BagBag.Models.PaymentMethod

@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/Management/Views/Shared/_AdministratorLayout.cshtml";
}

<h2 class=" text-center">Update Information's Payment Method</h2>
<div><a href="@Url.Action("Index","PaymentMethods")" class="btn btn-info">Manage</a></div>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
       
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.PaymentId)

        <div class="form-group">
            @Html.LabelFor(model => model.PaymentName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PaymentName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PaymentName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

TLTN/BagBag/Areas/Management/Views/PaymentMethods/Index.cshtml
@model IEnumerable<BagBag.Models.PaymentMethod>

@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Management/Views/Shared/_AdministratorLayout.cshtml";
}

<h2 class=" text-center">Management Payment Method</h2>

<p>
    <a href="@Url.Action("Create", "PaymentMethods")" class="btn btn-info">
        Create
    </a>
</p>
@Html.Raw(TempData["msg1"])
<table class="table table-striped table-bordered" id="tablefillset">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.PaymentName)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.PaymentName)
                </td>
                <td>
                    <a href="@Url.Action("Edit", "PaymentMethods", new { id = item.PaymentId})" class="btn btn-success">
                        <i class="fa fa-pencil"></i>
                        <span>

                        </span>
                    </a>
                    |
                    <a href="@Url.Action("Details", "PaymentMethods", new { id = item.PaymentId })" class="btn btn-primary">
                        <i class="fa fa-list-alt"></i>
                        <span>

                        </span>
                    </a>
                    |
                    <a href="@Url.Action("Delete", "PaymentMethods", new { id = item.PaymentId})" class="btn btn-danger">
                        <i class="fa fa-trash-o"></i>
                        <span>

                        </span>
                    </a>
                </td>
            </tr>
        }
    </tbody>
</table>