TLTN/BagBag/Areas/Management/Models/LoginViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;
namespace BagBag.Areas.Management.Models
{
    public class LoginViewModel
    {
        [Required(ErrorMessage ="Username không được để rỗng")]
        public string EmployeeCode { get; set; }
        [Required(ErrorMessage ="Password không được để rỗng")]
        public string EmployeePass { get; set; }
    }
}

TLTN/BagBag/Models/LoginUser.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace BagBag.Models
{
    public class LoginUser
    {
        [Required(ErrorMessage = "Username can not null")]
        public string CustomerCode { get; set; }
        [Required(ErrorMessage = "Password can not null")]
        public string CustomerPass { get; set; }
    }
}

TLTN/BagBag/Areas/Management/Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BagBag.Areas.Management.Models;
using BagBag.Models;
using CaptchaMvc.HtmlHelpers;

namespace BagBag.Areas.Management.Controllers
{
    public class LoginController : Controller
    {
        // GET: Management/Login
        public ActionResult Login()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Login(LoginViewModel model)
        {
            if (ModelState.IsValid && this.IsCaptchaValid("Capcha is not valid"))
            {
                var result = CheckRegister(model.EmployeeCode, model.EmployeePass);
                if (result)
                {
                    Session["employee"] = model.EmployeeCode;
                    return RedirectToAction("Index", "Page");

                }
                else
                {
                    ModelState.AddModelError("", "Please check username  or Password!");
                }
            }
            return View("Login");
        }
        public static bool CheckRegister(string employeecode, string employeepassword)
        {
            //var pass = Encrypt.MD5_Encode(password);


            var encrpytedPassword = Encrypt.MD5_Encode(employeepassword);
            using (MyBagBagEntities db = new MyBagBagEntities())
            {
                var singin = from p in db.Employees
                             where p.EmployeeCode == employeecode && p.EmployeePass == encrpytedPassword
                             select p;
                return singin.Any();
            }

        }
        public ActionResult LogOff()
        {
            Session["employee"] = null;
            return RedirectToAction("Index", "Home");
        }
    }
}

TLTN/BagBag/Controllers/LoginUserController.cs
using BagBag.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BagBag.Controllers
{
    public class LoginUserController : Controller
    {
        public static bool CheckRegister(string username, string password)
        {
            var encrpytedPassword = Encrypt.MD5_Encode(password);
            using (MyBagBagEntities db = new MyBagBagEntities())
            {
                var singin = from p in db.Customers
                             where p.CustomerCode == username && p.CustomerPass == encrpytedPassword
                             select p;
                return singin.Any();
            }
        }
        // GET: LoginUser
        public ActionResult Login()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Login(LoginUser model)
        {
            if (ModelState.IsValid)
            {
                var result = CheckRegister(model.CustomerCode, model.CustomerPass);
                if (result)
                {
                    Session["username"] = model.CustomerCode;
                    return RedirectToAction("Index", "Home");
                }
                else
                {
                    return RedirectToAction("Login");
                }
            }
            return View("Login");
        }
        public ActionResult LoginCart()
        {
            return View();
        }
        [HttpPost]
        public ActionResult LoginCart(LoginUser model)
        {
            if (ModelState.IsValid)
            {
                var result = CheckRegister(model.CustomerCode, model.CustomerPass);
                if (result)
                {
                    Session["username"] = model.CustomerCode;
                    return RedirectToAction("ConfirmCheckOut", "Cart");
                }
                else
                {
                    return RedirectToAction("LoginCart");
                }
            }
            return View("LoginCart");
        }
        public ActionResult LogOff()
        {
            Session["username"] = null;
            return RedirectToAction("Index", "Home");
        }
    }
}

TLTN/BagBag/Views/LoginUser/Login.cshtml
@model BagBag.Models.Customer
@{
    ViewBag.Title = "Login";
    Layout = "~/Views/Shared/_UserLayout.cshtml";
}

<div class="login">
    <div class="wrap">
        <div class="col_1_of_login span_1_of_login">
            <h4 class="title">New Customers</h4>
            <p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan</p>
            <div class="button1">
                <a href="@Url.Action("Register","Registers")">Register</a>
            </div>
            <div class="clear"></div>
        </div>
        <div class="col_1_of_login span_1_of_login">
            <div class="login-title">
                <h4 class="title">Login</h4>
                <div id="loginbox" class="loginbox">
                    @using (Html.BeginForm("Login", "LoginUser", FormMethod.Post))
                    {
                        @Html.AntiForgeryToken()
                   
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                  
                            <fieldset class="input">
                                <p id="login-form-username">
                                    <label for="modlgn_username">Username</label>
                                   
                                    @Html.TextBoxFor(model => model.CustomerCode, new { @class = "inputbox", @size = "18", @id = "modlgn_username", @autofocus = "autofocus" })
                                </p>
                                <p id="login-form-password">
                                    <label for="modlgn_passwd">Password</label>
                                    
                                    @Html.PasswordFor(model => model.CustomerPass, new { @class = "inputbox", @size = "18", @id = "modlgn_passwd" })
                                </p>
                                <div class="remember">
                                  
                                    <input type="submit" name="Submit" class="button" value="Login"><div class="clear"></div>
                                </div>
                            </fieldset>
                      
                    }
                </div>
            </div>
        </div>
        <div class="clear"></div>
    </div>
</div>

TLTN/BagBag/Views/LoginUser/LoginCart.cshtml
@model BagBag.Models.Customer
@{
    ViewBag.Title = "LoginCart";
    Layout = "~/Views/Shared/_UserLayout.cshtml";
}

<div class="login">
<div class="wrap">
    <div class="col_1_of_login span_1_of_login">
        <h4 class="title">New Customers</h4>
        <p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan</p>
        <div class="button1">
            <a href="@Url.Action("Register","Registers")">Register</a>
        </div>
        <div class="clear"></div>
    </div>
    <div class="col_1_of_login span_1_of_login">
        <div class="login-title">
            <h4 class="title">Đăng Nhập </h4>
            <div id="loginbox" class="loginbox">
                @using (Html.BeginForm("Login", "LoginUser", FormMethod.Post))
                {
                    @Html.AntiForgeryToken()

                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                    <fieldset class="input">
                        <p id="login-form-username">
                            <label for="modlgn_username">Username</label>

                            @Html.TextBoxFor(model => model.CustomerCode, new { @class = "inputbox", @size = "18", @id = "modlgn_username", @autofocus = "autofocus" })
                        </p>
                        <p id="login-form-password">
                            <label for="modlgn_passwd">Password</label>

                            @Html.PasswordFor(model => model.CustomerPass, new { @class = "inputbox", @size = "18", @id = "modlgn_passwd" })
                        </p>
                        <div class="remember">
                            <p id="login-form-remember">
                                <label for="modlgn_remember"><a href="#">Forget Your Password ? </a></label>
                            </p>
                            <input type="submit" name="Submit" class="button" value="Login"><div class="clear"></div>
                        </div>
                    </fieldset>

                }
            </div>
        </div>
    </div>
    <div class="clear"></div>
</div>
</div>