TLTN/BagBag/Models/About.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BagBag.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class About
    {
        public int AboutId { get; set; }
        public string AboutUs { get; set; }
        public string AboutImg { get; set; }
        public string AboutDetails { get; set; }
        public string EmployeeCode { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}

TLTN/BagBag/Areas/Management/Controllers/AboutsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Data.Entity.Validation;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using BagBag.Models;

namespace BagBag.Areas.Management.Controllers
{
    public class AboutsController : BaseController
    {
        private MyBagBagEntities db = new MyBagBagEntities();

        // GET: Management/Abouts
        public ActionResult Index()
        {
            var abouts = db.Abouts.Include(a => a.Employee);
            return View(abouts.ToList());
        }

        // GET: Management/Abouts/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            About about = db.Abouts.Find(id);
            if (about == null)
            {
                return HttpNotFound();
            }
            return View(about);
        }

        // GET: Management/Abouts/Create
        public ActionResult Create()
        {
            ViewBag.EmployeeCode = new SelectList(db.Employees, "EmployeeCode", "EmployeeCode");
            return View();
        }

        // POST: Management/Abouts/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "AboutId,AboutUs,AboutDetails,EmployeeCode")] About about)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    db.Abouts.Add(about);
                    db.SaveChanges();
                }
                catch (DbEntityValidationException dbEx)
                {
                    foreach (var validationErrors in dbEx.EntityValidationErrors)
                    {
                        foreach (var validationError in validationErrors.ValidationErrors)
                        {
                            System.Console.WriteLine("Property: {0} Error: {1}", validationError.PropertyName, validationError.ErrorMessage);
                        }
                    }
                }
                return RedirectToAction("Index");
            }

            ViewBag.EmployeeCode = new SelectList(db.Employees, "EmployeeCode", "EmployeeCode", about.EmployeeCode);
            return View(about);
        }

        // GET: Management/Abouts/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            About about = db.Abouts.Find(id);
            if (about == null)
            {
                return HttpNotFound();
            }
            ViewBag.EmployeeCode = new SelectList(db.Employees, "EmployeeCode", "EmployeeCode", about.EmployeeCode);
            return View(about);
        }

        // POST: Management/Abouts/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "AboutId,AboutUs,AboutDetails,EmployeeCode")] About about)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    db.Entry(about).State = EntityState.Modified;
                    db.SaveChanges();
                }
                catch (DbEntityValidationException dbEx)
                {
                    foreach (var validationErrors in dbEx.EntityValidationErrors)
                    {
                        foreach (var validationError in validationErrors.ValidationErrors)
                        {
                            System.Console.WriteLine("Property: {0} Error: {1}", validationError.PropertyName, validationError.ErrorMessage);
                        }
                    }
                }
                return RedirectToAction("Index");
            }
            ViewBag.EmployeeCode = new SelectList(db.Employees, "EmployeeCode", "EmployeeCode", about.EmployeeCode);
            return View(about);
        }

        // GET: Management/Abouts/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            About about = db.Abouts.Find(id);
            if (about == null)
            {
                return HttpNotFound();
            }
            return View(about);
        }

        // POST: Management/Abouts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            try
            {
                About about = db.Abouts.Find(id);
                db.Abouts.Remove(about);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            catch (Exception e)
            {
                TempData["msg1"] = "<script>alert('Can not Delete Record');</script>";
                e.ToString();
            }
            return RedirectToAction("Index");
        }
        public ActionResult UploadAbout(int id)
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult UploadAbout(HttpPostedFileBase file, int id)
        {
            var defaultFolderToSaveFile = "~/myImg/About/" + id + "/";

            // Kiểm tra nếu chưa tồn tại thư mục trên thì tạo mới. 
            if (Directory.Exists(Server.MapPath(defaultFolderToSaveFile)) == false)
            {
                Directory.CreateDirectory(Server.MapPath(defaultFolderToSaveFile));
            }

            if (ModelState.IsValid)
            {
                // Kiểm tra nếu người dùng có chọn file
                if (file != null && file.ContentLength > 0)
                {
                    // Lấy tên file
                    var fileName = Path.GetFileName(file.FileName);
                    if (fileName != null)
                    {
                        var path = Path.Combine(Server.MapPath(defaultFolderToSaveFile), fileName);

                        var i = 1;
                        while (System.IO.File.Exists(path))
                        {
                            path = Path.Combine(Server.MapPath(defaultFolderToSaveFile), i + "_" + fileName);
                            i++;
                        }

                        // Upload file lên Server ở thư mục ~/myImg/
                        file.SaveAs(path);

                        // Lấy imageurl để lưu vào database, có định dạng "~/myImg/Vehicle/Id/ten_file.jpg"
                        var imageUrl = defaultFolderToSaveFile + fileName;
                        try
                        {
                            // Lưu thông tin image url vào product
                            var About = db.Abouts.Find(id);
                        About.AboutImg = imageUrl;
                        //Delivery.ImgDelivery = imageUrl;
                        db.SaveChanges();
                        }
                        catch (DbEntityValidationException dbEx)
                        {
                            foreach (var validationErrors in dbEx.EntityValidationErrors)
                            {
                                foreach (var validationError in validationErrors.ValidationErrors)
                                {
                                    System.Console.WriteLine("Property: {0} Error: {1}", validationError.PropertyName, validationError.ErrorMessage);
                                }
                            }
                        }
                        return RedirectToAction("Index");
                    }
                }
            }
            return View();
        }
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

TLTN/BagBag/Controllers/AboutController.cs
using BagBag.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BagBag.Controllers
{
    public class AboutController : Controller
    {
        // GET: About
        private MyBagBagEntities db = new MyBagBagEntities();
        public ActionResult About()
        {
            var abouts = db.Abouts;
            return View(abouts.ToList());
        }
    }
}

TLTN/BagBag/Areas/Management/Views/Abouts/Create.cshtml
@model BagBag.Models.About

@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/Management/Views/Shared/_AdministratorLayout.cshtml";
}

<h2 class=" text-center">About Us</h2>
<div><a href="@Url.Action("Index","Abouts")" class="btn btn-info">Manage</a></div>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
     
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.AboutUs, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AboutUs, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AboutUs, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AboutImg, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AboutImg, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AboutImg, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AboutDetails, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AboutDetails, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AboutDetails, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EmployeeCode, "EmployeeCode", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("EmployeeCode", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.EmployeeCode, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-info" />
            </div>
        </div>
    </div>
}

TLTN/BagBag/Areas/Management/Views/Abouts/Delete.cshtml
@model BagBag.Models.About

@{
    ViewBag.Title = "Delete";
    Layout = "~/Areas/Management/Views/Shared/_AdministratorLayout.cshtml";
}

<h3>Are you sure delete record?</h3>
<div>

    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.AboutUs)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AboutUs)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.AboutDetails)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AboutDetails)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Employee.EmployeeCode)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Employee.EmployeeCode)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-danger" /> |
            <a href="@Url.Action("Index","Abouts")" class="btn btn-info">Manage</a>
        </div>
    }
</div>

TLTN/BagBag/Areas/Management/Views/Abouts/Details.cshtml
@model BagBag.Models.About

@{
    ViewBag.Title = "Details";
    Layout = "~/Areas/Management/Views/Shared/_AdministratorLayout.cshtml";
}

<h2 class="text-center">About's Information</h2>
<a href="@Url.Action("Index","Abouts")" class="btn btn-info">Manage</a>

<div>

    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.AboutUs)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AboutUs)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.AboutDetails)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AboutDetails)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Employee.EmployeeCode)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Employee.EmployeeCode)
        </dd>

    </dl>
</div>
<p>
    <a href="@Url.Action("Edit", "Abouts", new { id = Model.AboutId })" class="btn btn-success">Edit</a>
</p>

TLTN/BagBag/Areas/Management/Views/Abouts/Edit.cshtml
@model BagBag.Models.About

@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/Management/Views/Shared/_AdministratorLayout.cshtml";
}

<h2 class="text-center">Update  About's Information</h2>
<div><a href="@Url.Action("Index","Abouts")" class="btn btn-info">Manage</a></div>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
  
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.AboutId)

        <div class="form-group">
            @Html.LabelFor(model => model.AboutUs, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AboutUs, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AboutUs, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AboutImg, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AboutImg, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AboutImg, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AboutDetails, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AboutDetails, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AboutDetails, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EmployeeCode, "EmployeeCode", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Employee Code", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.EmployeeCode, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Update" class="btn btn-info" />
            </div>
        </div>
    </div>
}

TLTN/BagBag/Areas/Management/Views/Abouts/Index.cshtml
@model IEnumerable<BagBag.Models.About>

@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Management/Views/Shared/_AdministratorLayout.cshtml";
}

<h2 class="text-center">About Us</h2>

<p>
    <a href="@Url.Action("Create", "Abouts")" class="btn btn-info">
        Add
    </a>
</p>
<table class="table table-striped table-bordered" id="tablefillset">
    <thead>
        <tr class="text-center">
            <th class="col-md-2 text-center"> About Us</th>
            <th class="col-md-1">
                @Html.DisplayNameFor(model => model.AboutUs)
            </th>
            <th class="col-md-4">
                @Html.DisplayNameFor(model => model.AboutDetails)
            </th>
            <th class="col-md-2">
                @Html.DisplayNameFor(model => model.Employee.EmployeeCode)
            </th>
            <th class="col-md-2"></th>
        </tr>
        </thead>
    <tbody>
        @foreach (var item in Model)
        {
        <tr class="text-center">
            
            <td>
                @if (String.IsNullOrEmpty(item.AboutImg) == false)
                {
                    <img style="width: 100px" src="@Url.Content(item.AboutImg)" />
                }
            </td>
           
            <td>
                @Html.DisplayFor(modelItem => item.AboutUs)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.AboutDetails)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Employee.EmployeeCode)
            </td>
            <td>
                <a href="@Url.Action("UploadAbout", "Abouts", new { id = item.AboutId})" class="btn btn-info">
                    <i class="fa fa-image"></i>
                    <span>

                    </span>
                </a>
                |
                <a href="@Url.Action("Edit", "Abouts", new { id = item.AboutId})" class="btn btn-success">
                    <i class="fa fa-pencil"></i>
                    <span>

                    </span>
                </a>
                |
                <a href="@Url.Action("Details", "Abouts", new { id = item.AboutId })" class="btn btn-primary">
                    <i class="fa fa-list-alt"></i>
                    <span>

                    </span>
                </a>
                |
                <a href="@Url.Action("Delete", "Abouts", new { id = item.AboutId })" class="btn btn-danger">
                    <i class="fa fa-trash-o"></i>
                    <span>

                    </span>
                </a>
            </td>
        </tr>
        }
    </tbody>
</table>

TLTN/BagBag/Areas/Management/Views/Abouts/UploadAbout.cshtml
@{
    ViewBag.Title = "UploadAbout";
    Layout = "~/Areas/Management/Views/Shared/_AdministratorLayout.cshtml";
}

<h2 class="text-center">Upload IMG</h2>
<div><a href="@Url.Action("Index","Abouts")" class="btn btn-info">Manage</a></div>

@using (Html.BeginForm("UploadAbout", "Abouts", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    <div class="form-inline text-center">
        <!-- File Upload -->
        <div class="form-group">

            <input type="file" class="form-control" name="file" />
            <br />
            <br />
            <input type="submit" value="Upload" class="btn btn-primary" />

        </div>
    </div>

}